---
- name: Check packages to be installed
  block:
  - name: "Check if packages are already installed" # noqa command-instead-of-module this runs faster
    ansible.builtin.command: "rpm -q {{ packages_list | join(' ') }}"
    register: rpm_info
    changed_when: rpm_info.failed

  rescue:
    - name: "Add missing packages to the yum install list"
      ansible.builtin.set_fact:
        packages_to_install: "{{ packages_to_install | default([]) + rpm_info.stdout_lines | map('regex_findall', 'package (.+) is not installed$') | flatten }}"
      when: rpm_info.failed

- name: "Install packages: {{ packages_to_install | join(',') }}"
  become: yes
  ansible.builtin.yum:
    name: "{{ packages_to_install }}"
    state: present
  when: packages_to_install | default([]) | length > 0
