argument_specs:
    main:
        options:
            keycloak_host:
                # line 3 of keycloak_realm/defaults/main.yml
                default: "localhost"
                description: "Hostname for rest calls"
                type: "str"
            keycloak_context:
                # line 5 of keycloak_realm/defaults/main.yml
                default: "/auth"
                description: "Context path for rest calls"
                type: "str"                
            keycloak_http_port:
                # line 4 of keycloak_realm/defaults/main.yml
                default: 8080
                description: "HTTP port"
                type: "int"
            keycloak_https_port:
                # line 5 of keycloak_realm/defaults/main.yml
                default: 8443
                description: "HTTPS port"
                type: "int"
            keycloak_management_http_port:
                # line 6 of keycloak_realm/defaults/main.yml
                default: 9990
                description: "Management port"
                type: "int"
            keycloak_admin_user:
                # line 10 of keycloak_realm/defaults/main.yml
                default: "admin"
                description: "Administration console user account"
                type: "str"
            keycloak_auth_realm:
                # line 11 of keycloak_realm/defaults/main.yml
                default: "master"
                description: "Name of the main authentication realm"
                type: "str"
            keycloak_auth_client:
                # line 12 of keycloak_realm/defaults/main.yml
                default: "admin-cli"
                description: "Authentication client for configuration REST calls"
                type: "str"
            keycloak_client_default_roles:
                # line 36 of keycloak_realm/defaults/main.yml
                default: "[]"
                description: "List of roles to configure as client default"
                type: "list"
            keycloak_client_public:
                # line 39 of keycloak_realm/defaults/main.yml
                default: true
                description: "Configure a public realm client"
                type: "bool"
            keycloak_client_web_origins:
                # line 42 of keycloak_realm/defaults/main.yml
                default: "+"
                description: "Web origins for realm client"
                type: "str"
            keycloak_client_users:
                # line 49 of keycloak_realm/defaults/main.yml
                default: "[]"
                description: "List of users to configure in the realm client"
                type: "list"
            keycloak_user_federation:
                # line 52 of keycloak_realm/defaults/main.yml
                default: "[]"
                description: "List of user federations to configure in the realm"
                type: "list"
            keycloak_admin_password:
                # line 5 of keycloak_realm/vars/main.yml
                required: true
                description: "Password for the administration console user account"
                type: "str"
            keycloak_realm:
                # line 8 of keycloak_realm/vars/main.yml
                required: true
                description: "Name of the realm to be configured"
                type: "str"
            keycloak_clients:
                # line 11 of keycloak_realm/vars/main.yml
                default: "[]"
                description: "List of client declarations for the realm"
                type: "list"
            keycloak_url:
                # line 14 of keycloak_realm/vars/main.yml
                default: "http://{{ keycloak_host }}:{{ keycloak_http_port }}"
                description: "URL for configuration rest calls"
                type: "str"
            keycloak_management_url:
                # line 15 of keycloak_realm/vars/main.yml
                default: "http://{{ keycloak_host }}:{{ keycloak_management_http_port }}"
                description: "URL for management console rest calls"
                type: "str"
    downstream:
        options:
            sso_version:
                default: "7.5.0"
                description: "Red Hat Single Sign-On version"
                type: "str"
            sso_dest:
                default: "/opt/sso"
                description: "Root installation directory"
                type: "str"
            sso_installdir:
                default: "{{ sso_dest }}/rh-sso-{{ sso_version.split('.')[0] }}.{{ sso_version.split('.')[1] }}"
                description: "Installation path for Red Hat SSO"
                type: "str"
            sso_apply_patches:
                default: False
                description: "Install Red Hat SSO most recent cumulative patch"
                type: "bool"
            sso_enable:
                default: True
                description: "Enable Red Hat Single Sign-on installation"
                type: "str"
